name: covid19_info
description: App to monitor statistics and news about Covid19 especially in Nepal.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  rxdart: ^0.24.0
  flutter_bloc: ^4.0.0
  assets_audio_player: ^1.6.0
  line_awesome_icons: ^1.0.4+2
  google_nav_bar: ^2.1.0
  simple_coverflow: ^0.0.8
  loading_indicator: ^1.1.0
  auto_size_text: ^2.1.0
  sliding_up_panel: ^1.0.1
  url_launcher: ^5.4.2
  flutter_map: ^0.9.0
  fl_chart: ^0.8.7
  intl: ^0.16.1
  device_preview: ^0.4.4
  animator: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.4
  flutter_native_splash: ^0.1.9

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  image: assets/icon/splash.png
  color: "00796B"
  android_disable_fullscreen: true
  

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/icon.png

  fonts:
    - family: Sen
      fonts:
        - asset: assets/fonts/Sen-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sen-Regular.ttf
          weight: 500

    - family: Sura
      fonts:
        - asset: assets/fonts/Sura-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sura-Regular.ttf
          weight: 500